name: platform_device_id_example
description: Demonstrates how to use the platform_device_id plugin.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.12.2
  flutter: ">=3.44.4"

dependencies:
  flutter:
    sdk: flutter

  platform_device_id_plus:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

