name: platform_device_id_plus
description: This is upgraded version of platform_device_id
version: 1.0.7
homepage: https://github.com/acmonetwork/platform_device_id_plus

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  platform_device_id_platform_interface: ^1.0.0
  platform_device_id_macos: ^1.0.0
  platform_device_id_linux: ^1.0.0
  platform_device_id_web: ^1.0.0
  platform_device_id_windows: ^1.0.0
  device_info_plus: ^11.3.0
  android_id: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.di1shuai.platform_device_id
        pluginClass: PlatformDeviceIdPlugin
      ios:
        pluginClass: PlatformDeviceIdPlugin
      macos:
        pluginClass: PlatformDeviceIdMacosPlugin
      linux:
        default_package: platform_device_id_linux
      web:
        default_package: platform_device_id_web
      windows:
        default_package: platform_device_id_windows

